### PR TITLE
Support for namespace constraints and areas.

### PR DESCRIPTION
**Pull request by salarcode**
Hi,
I have added support for namespace constraints and Area.

### CODE REVIEW

**Comment by atas** [comment]
Thanks Salar, I was busy for some time and couldn't update it. Nice work.

**Comment by salarcode** [comment]
You're welcome.
But I have changed readme.md file for my fork.
You may want to restore it :)

**Comment by atas** [comment]
Huh, Github mixed up my last message.

I see your name at the end, and that's okay. 
I do not "own" this library, it's free, whoever improves should put their name. I hope it will be useful for more people :) ASP.NET MVC's default urls are ugly...

**Comment by salarcode** [comment]
Thanks about that,
But i meant the intro part of the file which it points to the release page of my form.
Download link to be specific.
And yeah MVC urls are ugly :)

**Comment by atas** [comment]
Let's keep it for now. I'll build & test it and put it also NuGet system. When I update the NuGet package with this version, I'll point that link to NuGet.
I'll also put your name in NuGet list.
I'm a bit occupied these days, so I'll do it at the weekend, hopefully!

**Comment by salarcode** [comment]
Thanks, that's kind of you, i'm just publishing the changes I'm making on open-source projects.
Looking forward for the nuget package.

**Pull request merged**
